# Generated by Django 5.2.1 on 2025-06-21 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Main Region',
                'verbose_name_plural': 'Main Regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_regions', to='region.region')),
            ],
            options={
                'verbose_name': 'Sub Region',
                'verbose_name_plural': 'Sub Regions',
                'ordering': ['name'],
                'unique_together': {('name', 'parent_region')},
            },
        ),
    ]
