# Generated by Django 5.2.1 on 2025-06-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=100, unique=True)),
                ('rarity', models.IntegerField()),
                ('weapon_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
            },
        ),
    ]
