# Generated by Django 5.2.1 on 2025-06-29 03:18

import django.db.models.deletion
import weapon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=100, unique=True)),
                ('rarity', models.IntegerField()),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to=weapon.models.weapon_icon_upload_path)),
                ('weapon_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weapon.weapontype')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
                'ordering': ['weapon_name'],
            },
        ),
    ]
