# Generated by Django 5.2.1 on 2025-06-03 17:04

import weapon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=weapon.models.get_weapon_image_path)),
                ('tipe_senjata', models.CharField(max_length=50)),
                ('rarity', models.IntegerField()),
                ('stat_utama', models.FloatField(blank=True, null=True)),
                ('stat_kedua', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_pasif', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Weapons',
            },
        ),
    ]
