# Generated by Django 5.2.1 on 2025-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='base_atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='passive_skill_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='secondary_stat',
            field=models.CharField(choices=[('ATK%', 'ATK%'), ('DEF%', 'DEF%'), ('HP%', 'HP%'), ('Energy Regen', 'Energy Regen'), ('Crit Rate', 'Crit Rate'), ('Crit DMG', 'Crit DMG')], default='ATK%', max_length=50),
        ),
        migrations.AddField(
            model_name='weapon',
            name='secondary_value',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='weapons/icons/'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='rarity',
            field=models.IntegerField(default=1),
        ),
    ]
