# Generated by Django 5.2.1 on 2025-07-02 04:13

import weapon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0001_initial'),
    ]

    operations = [
        
    ]
