# Generated by Django 5.2.1 on 2025-07-01 19:18

import weapon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0002_weapon_base_atk_weapon_passive_skill_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='icon_weapon_type',
            field=models.ImageField(blank=True, null=True, upload_to='weapontype/'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=weapon.models.weapon_icon_upload_path),
        ),
    ]
