# Generated by Django 5.2.1 on 2025-07-02 04:33

import weapon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0002_alter_weapontype_options_weapon_base_atk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapontype',
            options={'ordering': ['name'], 'verbose_name': 'Weapon Type', 'verbose_name_plural': 'Weapon Types'},
        )
    ]
