# Generated by Django 5.2.1 on 2025-07-02 04:35

import weapon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0003_alter_weapontype_options_weapon_base_atk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapontype',
            options={},
        )
        
    ]
