# Generated by Django 5.2.1 on 2025-07-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0003_weapontype_icon_weapon_type_alter_weapon_icon_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapontype',
            options={'ordering': ['name'], 'verbose_name': 'Weapon_Type', 'verbose_name_plural': 'Weapons Types'},
        ),
    ]
