# Generated by Django 5.2.1 on 2025-07-03 02:29

import weapon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0005_weapon_base_atk_weapon_passive_skill_description_and_more'),
    ]

    operations = [
    ]
