# Generated by Django 5.2.1 on 2025-05-10 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('energy', models.FloatField()),
                ('crit_rate', models.FloatField()),
                ('crit_dmg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FinalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('energy', models.FloatField()),
                ('crit_rate', models.FloatField()),
                ('crit_dmg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('element', models.CharField(max_length=50)),
                ('weapon_type', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='character/icon/')),
                ('splash', models.ImageField(upload_to='character/splash/')),
                ('banner_sprite', models.ImageField(upload_to='character/banner_sprite/')),
                ('profile', models.ImageField(upload_to='character/profile/')),
                ('base_stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='add_character.basestat')),
                ('final_stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='add_character.finalstat')),
            ],
        ),
    ]
