# Generated by Django 5.2.1 on 2025-06-03 17:04

import resonators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resonator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=100, unique=True)),
                ('icon_gambar', models.ImageField(blank=True, null=True, upload_to=resonators.models.get_resonator_icon_path)),
                ('render_gambar', models.ImageField(blank=True, null=True, upload_to=resonators.models.get_resonator_render_path)),
                ('convene_gambar', models.ImageField(blank=True, null=True, upload_to=resonators.models.get_resonator_convene_path)),
                ('rarity', models.CharField(blank=True, max_length=10, null=True)),
                ('weapon', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.CharField(blank=True, max_length=20, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=100, null=True)),
                ('attribute', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('atk', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('energy', models.IntegerField(blank=True, null=True)),
                ('crit_rate', models.IntegerField(blank=True, null=True)),
                ('crit_dmg', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resonator',
                'verbose_name_plural': 'Resonators',
            },
        ),
    ]
