# Generated by Django 5.2.1 on 2025-06-29 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combat', '0001_initial'),
        ('region', '0001_initial'),
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resonator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official name of the Resonator.', max_length=100, unique=True)),
                ('rarity', models.IntegerField(help_text='The star rarity of the Resonator (e.g., 4 or 5).')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='combat.attribute')),
                ('birthplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.region')),
                ('role', models.ManyToManyField(blank=True, null=True, to='combat.role')),
                ('weapon_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weapon.weapontype')),
            ],
            options={
                'verbose_name': 'Resonator',
                'verbose_name_plural': 'Resonators',
                'ordering': ['name'],
            },
        ),
    ]
