# Generated by Django 5.2.1 on 2025-06-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
        ('resonators', '0001_initial'),
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resonator',
            name='recommended_echos',
            field=models.ManyToManyField(related_name='recommended_for_resonators_echo', through='resonators.ResonatorRecommendedEcho', to='echo.echo'),
        ),
        migrations.AddField(
            model_name='resonator',
            name='recommended_sonatas',
            field=models.ManyToManyField(related_name='recommended_for_resonators_sonata', through='resonators.ResonatorRecommendedSonata', to='echo.sonata'),
        ),
        migrations.AddField(
            model_name='resonator',
            name='recommended_weapons',
            field=models.ManyToManyField(related_name='recommended_for_resonators', through='resonators.ResonatorRecommendedWeapon', to='weapon.weapon'),
        ),
    ]
