# Generated by Django 5.2.1 on 2025-06-19 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
        ('resonators', '0001_initial'),
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resonator',
            old_name='weapon',
            new_name='weapon_type',
        ),
        migrations.CreateModel(
            name='ResonatorRecommendedEcho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.IntegerField(choices=[(1, 'Best in Slot'), (2, 'Great Alternative'), (3, 'Good Option'), (4, 'Situational')], default=1, help_text='Tingkat kelayakan set Echo untuk karakter ini')),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan tentang rekomendasi Echo ini.')),
                ('echo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo.echo')),
                ('resonator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resonators.resonator')),
            ],
            options={
                'verbose_name': 'Resonator Recommended Echo',
                'verbose_name_plural': 'Resonator Recommended Echoes',
                'ordering': ['priority_level'],
                'unique_together': {('resonator', 'echo')},
            },
        ),
        migrations.AddField(
            model_name='resonator',
            name='recommended_echos',
            field=models.ManyToManyField(related_name='recommended_for_resonators_echo', through='resonators.ResonatorRecommendedEcho', to='echo.echo'),
        ),
        migrations.CreateModel(
            name='ResonatorRecommendedSonata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.IntegerField(choices=[(1, 'Best in Slot'), (2, 'Great Alternative'), (3, 'Good Option'), (4, 'Situational')], default=1, help_text='Tingkat kelayakan Sonata untuk karakter ini')),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan tentang rekomendasi Sonata ini.')),
                ('resonator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resonators.resonator')),
                ('sonata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo.sonata')),
            ],
            options={
                'verbose_name': 'Resonator Recommended Sonata',
                'verbose_name_plural': 'Resonator Recommended Sonatas',
                'ordering': ['priority_level'],
                'unique_together': {('resonator', 'sonata')},
            },
        ),
        migrations.AddField(
            model_name='resonator',
            name='recommended_sonatas',
            field=models.ManyToManyField(related_name='recommended_for_resonators_sonata', through='resonators.ResonatorRecommendedSonata', to='echo.sonata'),
        ),
        migrations.CreateModel(
            name='ResonatorRecommendedWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.IntegerField(choices=[(1, 'Best in Slot'), (2, 'Great Alternative'), (3, 'Good Option'), (4, 'Situational')], default=1, help_text='Tingkat kelayakan senjata untuk karakter ini (1=terbaik, 4=situasional)')),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan tentang rekomendasi senjata ini.')),
                ('resonator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resonators.resonator')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapon.weapon')),
            ],
            options={
                'verbose_name': 'Resonator Recommended Weapon',
                'verbose_name_plural': 'Resonator Recommended Weapons',
                'ordering': ['priority_level'],
                'unique_together': {('resonator', 'weapon')},
            },
        ),
        migrations.AddField(
            model_name='resonator',
            name='recommended_weapons',
            field=models.ManyToManyField(related_name='recommended_for_resonators', through='resonators.ResonatorRecommendedWeapon', to='weapon.weapon'),
        ),
    ]
