# Generated by Django 5.2.1 on 2025-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
        ('resonators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resonator',
            name='role',
            field=models.ManyToManyField(blank=True, to='combat.role'),
        ),
    ]
