# Generated by Django 5.2.1 on 2025-06-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resonators', '0002_resonator_recommended_echos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resonator',
            name='recommended_echos',
        ),
        migrations.RemoveField(
            model_name='resonator',
            name='recommended_sonatas',
        ),
        migrations.RemoveField(
            model_name='resonator',
            name='recommended_weapons',
        ),
    ]
