# Generated by Django 5.2.1 on 2025-06-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
        ('resonators', '0003_remove_resonator_recommended_echos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resonator',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='combat.role'),
        ),
    ]
