# Generated by Django 5.2.1 on 2025-06-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resonators', '0004_alter_resonator_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resonator',
            old_name='roles',
            new_name='role',
        ),
    ]
