# Generated by Django 5.2.1 on 2025-06-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
        ('region', '0001_initial'),
        ('resonators', '0005_rename_roles_resonator_role'),
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resonator',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='combat.attribute'),
        ),
        migrations.AlterField(
            model_name='resonator',
            name='birthplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.region'),
        ),
        migrations.AlterField(
            model_name='resonator',
            name='weapon_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weapon.weapontype'),
        ),
    ]
