# Generated by Django 5.2.1 on 2025-06-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
        ('resonators', '0006_alter_resonator_attribute_alter_resonator_birthplace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resonator',
            name='role',
        ),
        migrations.AddField(
            model_name='resonator',
            name='role',
            field=models.ManyToManyField(blank=True, to='combat.role'),
        ),
    ]
