# Generated by Django 5.2.1 on 2025-06-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
        ('resonators', '0007_remove_resonator_role_resonator_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resonator',
            name='role',
        ),
        migrations.AddField(
            model_name='resonator',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='combat.role'),
        ),
    ]
