# Generated by Django 5.2.1 on 2025-06-03 17:04

import echo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to=echo.models.get_echo_image_path)),
                ('set_bonus_2pc', models.TextField(blank=True, null=True)),
                ('set_bonus_5pc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Echoes',
            },
        ),
    ]
