# Generated by Django 5.2.1 on 2025-06-29 03:18

import echo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sonata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_sonata', models.ImageField(blank=True, null=True, upload_to=echo.models.sonata_icon_upload_path)),
            ],
            options={
                'verbose_name': 'Sonata',
                'verbose_name_plural': 'Sonatas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost', models.IntegerField()),
                ('icon_echo', models.ImageField(blank=True, null=True, upload_to=echo.models.echo_icon_upload_path)),
                ('sonatas', models.ManyToManyField(blank=True, to='echo.sonata')),
            ],
            options={
                'verbose_name': 'Echo',
                'verbose_name_plural': 'Echos',
                'ordering': ['name'],
            },
        ),
    ]
