# Generated by Django 5.2.1 on 2025-06-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sonata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sonata',
                'verbose_name_plural': 'Sonatas',
            },
        ),
        migrations.CreateModel(
            name='Echo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost', models.IntegerField()),
                ('sonatas', models.ManyToManyField(related_name='echos', to='echo.sonata')),
            ],
            options={
                'verbose_name': 'Echo',
                'verbose_name_plural': 'Echos',
            },
        ),
    ]
