# Generated by Django 5.2.1 on 2025-07-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resonators', '0002_alter_resonator_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Skill/Serangan Utama')),
                ('description', models.TextField(verbose_name='Deskripsi Combat')),
                ('skill_type_category', models.CharField(choices=[('Basic Attack', 'Basic Attack'), ('Heavy Attack', 'Heavy Attack'), ('Mid-air Attack', 'Mid-air Attack'), ('Dodge Counter', 'Dodge Counter'), ('Resonance Skill', 'Resonance Skill'), ('Resonance Liberation', 'Resonance Liberation'), ('Intro Skill', 'Intro Skill'), ('Outro Skill', 'Outro Skill'), ('Forte Circuit', 'Forte Circuit')], max_length=50, verbose_name='Kategori Tipe Skill')),
                ('resonator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_skills', to='resonators.resonator', verbose_name='Resonator')),
            ],
            options={
                'verbose_name': 'Skill Resonator',
                'verbose_name_plural': 'Skill Resonator',
                'unique_together': {('resonator', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SkillMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_name', models.CharField(max_length=200, verbose_name='Nama Serangan (Detail)')),
                ('multiplier_value', models.FloatField(verbose_name='Nilai Multiplier (%)')),
                ('attack_type', models.CharField(choices=[('basic', 'Basic Attack'), ('heavy', 'Heavy Attack'), ('skill', 'Resonance Skill'), ('liberation', 'Resonance Liberation'), ('intro', 'Intro Skill'), ('outro', 'Outro Skill'), ('forte', 'Forte Circuit')], max_length=50, verbose_name='Tipe Perhitungan DMG Bonus')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', to='damager.skill', verbose_name='Skill Terkait')),
            ],
            options={
                'verbose_name': 'Multiplier Skill Resonator',
                'verbose_name_plural': 'Multiplier Skill Resonator',
                'unique_together': {('skill', 'attack_name')},
            },
        ),
    ]
